create sequence hibernate_sequence start 1 increment 1;
create table catalog (id int8 not null, product_name varchar(255), product_price int4 not null, category_id int8, primary key (id));
create table catalog_aud (id int8 not null, rev int4 not null, revtype int2, product_name varchar(255), product_price int4, category_id int8, primary key (id, rev));
create table category (id int8 not null, category_name varchar(255), primary key (id));
create table category_aud (id int8 not null, rev int4 not null, revtype int2, category_name varchar(255), primary key (id, rev));
create table revinfo (rev int4 not null, revtstmp int8, primary key (rev));
alter table if exists catalog add constraint FK4e0jibokb2403yseeqvt618wh foreign key (category_id) references category;
alter table if exists catalog_aud add constraint FKf84e7oabeh119umo636nwfd6g foreign key (rev) references revinfo;
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
create sequence hibernate_sequence start 1 increment 1;
create table catalog (id int8 not null, product_name varchar(255), product_price int4 not null, category_id int8, primary key (id));
create table catalog_aud (id int8 not null, rev int4 not null, revtype int2, product_name varchar(255), product_price int4, category_id int8, primary key (id, rev));
create table category (id int8 not null, category_name varchar(255), primary key (id));
create table category_aud (id int8 not null, rev int4 not null, revtype int2, category_name varchar(255), primary key (id, rev));
create table revinfo (rev int4 not null, revtstmp int8, primary key (rev));
alter table if exists catalog add constraint FK4e0jibokb2403yseeqvt618wh foreign key (category_id) references category;
alter table if exists catalog_aud add constraint FKf84e7oabeh119umo636nwfd6g foreign key (rev) references revinfo;
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
create sequence hibernate_sequence start 1 increment 1;
create table catalog (id int8 not null, product_name varchar(255), product_price int4 not null, category_id int8, primary key (id));
create table catalog_aud (id int8 not null, rev int4 not null, revtype int2, product_name varchar(255), product_price int4, category_id int8, primary key (id, rev));
create table category (id int8 not null, category_name varchar(255), primary key (id));
create table category_aud (id int8 not null, rev int4 not null, revtype int2, category_name varchar(255), primary key (id, rev));
create table revinfo (rev int4 not null, revtstmp int8, primary key (rev));
alter table if exists catalog add constraint FK4e0jibokb2403yseeqvt618wh foreign key (category_id) references category;
alter table if exists catalog_aud add constraint FKf84e7oabeh119umo636nwfd6g foreign key (rev) references revinfo;
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
create sequence hibernate_sequence start 1 increment 1;
create table catalog (id int8 not null, product_name varchar(255), product_price int4 not null, category_id int8, primary key (id));
create table catalog_aud (id int8 not null, rev int4 not null, revtype int2, product_name varchar(255), product_price int4, category_id int8, primary key (id, rev));
create table category (id int8 not null, category_name varchar(255), primary key (id));
create table category_aud (id int8 not null, rev int4 not null, revtype int2, category_name varchar(255), primary key (id, rev));
create table revinfo (rev int4 not null, revtstmp int8, primary key (rev));
alter table if exists catalog add constraint FK4e0jibokb2403yseeqvt618wh foreign key (category_id) references category;
alter table if exists catalog_aud add constraint FKf84e7oabeh119umo636nwfd6g foreign key (rev) references revinfo;
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
create sequence hibernate_sequence start 1 increment 1;
create table catalog (id int8 not null, product_name varchar(255), product_price int4 not null, category_id int8, primary key (id));
create table catalog_aud (id int8 not null, rev int4 not null, revtype int2, product_name varchar(255), product_price int4, category_id int8, primary key (id, rev));
create table category (id int8 not null, category_name varchar(255), primary key (id));
create table category_aud (id int8 not null, rev int4 not null, revtype int2, category_name varchar(255), primary key (id, rev));
create table revinfo (rev int4 not null, revtstmp int8, primary key (rev));
alter table if exists catalog add constraint FK4e0jibokb2403yseeqvt618wh foreign key (category_id) references category;
alter table if exists catalog_aud add constraint FKf84e7oabeh119umo636nwfd6g foreign key (rev) references revinfo;
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
create sequence hibernate_sequence start 1 increment 1;
create table catalog (id int8 not null, product_name varchar(255), product_price int4 not null, category_id int8, primary key (id));
create table catalog_aud (id int8 not null, rev int4 not null, revtype int2, product_name varchar(255), product_price int4, category_id int8, primary key (id, rev));
create table category (id int8 not null, category_name varchar(255), primary key (id));
create table category_aud (id int8 not null, rev int4 not null, revtype int2, category_name varchar(255), primary key (id, rev));
create table revinfo (rev int4 not null, revtstmp int8, primary key (rev));
alter table if exists catalog add constraint FK4e0jibokb2403yseeqvt618wh foreign key (category_id) references category;
alter table if exists catalog_aud add constraint FKf84e7oabeh119umo636nwfd6g foreign key (rev) references revinfo;
alter table if exists category_aud add constraint FKc9m640crhsib2ws80um6xuk1w foreign key (rev) references revinfo;
