server:
  port: 8081
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webuni-webshop
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
  instance:
    prefer-ip-address: true