server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
    hostname: localhost  

spring:
  cloud:
    gateway:
      routes:
      - id: catalog
        uri: lb://catalog
        predicates:
        - Path=/catalog/**
        filters:
        - RewritePath=/catalog(?<segment>/?.*), /api/catalog$\{segment}
      - id: category
        uri: lb://catalog
        predicates:
        - Path=/category/**
        filters:
        - RewritePath=/category(?<segment>/?.*), /api/category$\{segment}
      - id: address
        uri: lb://order-service
        predicates:
        - Path=/address/**
        filters:
        - RewritePath=/address(?<segment>/?.*), /api/address$\{segment}
      - id: order
        uri: lb://order-service
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order(?<segment>/?.*), /api/order$\{segment}
      - id: user
        uri: lb://user-service
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user(?<segment>/?.*), /api/user$\{segment}